# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default=b'', max_length=500)),
                ('project_name', models.CharField(default=b'', max_length=250)),
                ('username', models.CharField(default=b'', max_length=250)),
                ('password', models.CharField(default=b'', max_length=250)),
            ],
        ),
    ]
